version: "3.8"
services:
  frontend:
    image: jhamilton31/frontend:${app_version}
    build: /frontend
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - backend

  backend:
    image: jhamilton31/backend:${app_version}
    build: /backend
    ports:
      - target: 5001
        published: 5001
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}

  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend