apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jhamilton31/backend:latest
          env:
            # SQL PASS
            - name: MYSQL_ROOT_PASSWORD
              value: password
              # DB PASS
            - name: DB_PASSWORD
              value: password
            # TEST DB URI
            - name: TEST_DATABASE_URI
              value: mysql+pymysql://admin:password@testdb.c0oxn6eqdeoq.eu-west-2.rds.amazonaws.com:3306/testdb
            # DB URI
            - name: DATABASE_URI
              value: mysql+pymysql://admin:password@deploydb.c0oxn6eqdeoq.eu-west-2.rds.amazonaws.com:3306/users
            # SECRET KEY
            - name: SECRET_KEY
              value: password
            # MYSQL DATABASE
            - name : MYSQL_DATABASE
              value: mysql
          ports:
            - containerPort: 5001